#! /bin/sh
### BEGIN INIT INFO
# Provides:          ibuntubuilder-firstboot
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run firstboot items for bodhibuilder after a remastered system has been installed
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
    #REM302
    if [ "`cat /proc/cmdline | grep casper`" = "" ]; then # run thru this if it's NOT an ISO
        [ "$VERBOSE" != no ] && log_begin_msg "Running ibuntubuilder-firstboot"
        # Removes this script from boot:
        (sleep 60 && update-rc.d -f bodhibuilder-firstboot remove) &
        sed -i -e 's/root:x:/root:!:/g' /etc/shadow
        ## Ubiquity
            # Remove ubiquity icon from desktop
            yes | rm -rf /home/*/Desktop/ubiquity*.desktop
            yes | rm -rf /home/*/Desktop/UBIQUITY*.desktop
            yes | rm -rf /usr/share/applications/UBIQUITY.desktop
            # Remove ubiquity from menus
            sed -i -e 's/NoDisplay=false/NoDisplay=true/' /usr/share/applications/ubiquity.desktop
            sed -i -e 's/Hidden=false/Hidden=true/' /usr/share/applications/ubiquity.desktop

        
        # Restore sources.list from source OS
        if [ -e /etc/ibuntubuilder/apt/sources.list_BB ] ; then
          yes | mv /etc/apt/sources.list /etc/apt/sources.list_ORIG
          yes | mv /etc/ibuntubuilder/apt/sources.list_BB /etc/apt/sources.list
          sleep 1
        fi
        # Remove any remaining cdrom repos that may be in sources.list
        sed -i '/cdrom:/d' /etc/apt/sources.list &> /dev/null

        # Replace OS grub with ibuntubuilder's custom grub
        yes | cp -f /etc/default/grub.ibuntu /etc/default/grub
        sed -i "s/^DISTRIB_DESCRIPTION=.*$/DISTRIB_DESCRIPTION=\"__DISTNAME__\"/" /etc/lsb-release
        if ! [ -f $FLAG ]; then
        sed -i "/NAME=/c\NAME=\"__LIVECDLABEL__\"/" /etc/os-release
        sed -i '/VARIANT=/c\VARIANT="Lix Nur -BETA-"' /etc/os-release
        sed -i "/PRETTY/c\PRETTY_NAME=\"__DISTNAME__\"/" /etc/os-release
        sed -i '/VERSION_ID/c\VERSION_ID="2.0"' /etc/os-release
        sed -i '/HOME_URL/c\HOME_URL="https://ibuntuos.com"' /etc/os-release
        sed -i "/DISTRIB_DESCRIPTION/c\DISTRIB_DESCRIPTION=\"__DISTNAME__\"/" /etc/lsb-release
        cd /
        for i in $(find -name systemsettingsrc); do
            sed -i '/Recent Files/d' $i
        done
        find -name "start.sh" -type f -delete
        #find -name "ubiquityib.desktop" -type f -delete

fi
        update-grub

        ################################################
        ### CUSTOM COMMANDS
        #
        # Commands entered into this section will be run only when
        # after the system has been installed and booted for the
        # first time, and never again.
        #
        ### Place your custom commands below this line
        
        
        ### Place your custom commands above this line
        ################################################
        
        ES=$?
        [ "$VERBOSE" != no ] && log_end_msg $ES
        return $ES
    else # run through this if it IS an ISO
        logger bodhibuilder ISO booted
        sleep 1
        # Remove any cdrom: repos that may be in sources.list
        sed -i '/cdrom:/d' /etc/apt/sources.list &> /dev/null
        
    fi
}


case "$1" in
    start)
        do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

